packaging_format = 2

id = "cjdns"
name = "Cjdns"

description.en = "Encrypted IPv6 network"
description.fr = "Réseau IPv6 chiffré"

version = "22.7~ynh2"

maintainers = ["dkoukoul"]

[upstream]
license = "GPL-3.0"
code = "https://github.com/cjdelisle/cjdns/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = ["amd64","arm64"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources]
        [resources.sources.main]
        amd64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdns_ynh_x86_64.tar.gz"
        amd64.sha256 = "ec4cea5226b8896c61d6db1736718f2f57a9f5e1303e3c3a1ca7cea445e14370"
        arm64.url = "https://github.com/dkoukoul/cjdns/releases/download/v22-7/cjdns_ynh_linux_arm64.tar.gz"
        arm64.sha256 = "a9cfece03bd3f4b163f46140cb2bd513a4dac826d7a038c3b87636fd0ac8e19e"
        in_subdir = false
        
    [resources.system_user]
    
    [resources.install_dir]

    [resources.ports]

    [resources.permissions]

    [resources.apt]
    packages = "curl, jq"
